
# ARG OWNER=jupyter
# ARG BASE_CONTAINER=$OWNER/scipy-notebook
# FROM $BASE_CONTAINER
FROM tensorflow/tensorflow:latest-gpu-jupyter

LABEL maintainer="Natron Tech <support@natron.io>"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]